version: "3"

services:
  backend:
    build: ./Backend
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/staticfiles:/app/staticfiles

  frontend:
    build: ./Frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
